### ISSUE TITLE
Items without "Name" crashes program when you try to edit them

### ISSUE THREAD

**Issue by evolite** [PathOfBuildingCommunity/PathOfBuilding#1135]
This patch introduced a way to generate items (through harvest crafting) that lose their name, they only have a type

![Path_of_Building_2ZvomuL3CA](https://user-images.githubusercontent.com/1220440/86397451-1d45e600-bca4-11ea-9fc4-1972a4ed46ac.png)

This crashes PoB when you try to edit them in PoB, and you will lose the gem when you save and open PoB again.

![Path_of_Building_lvc4BUEee3](https://user-images.githubusercontent.com/1220440/86397267-ce984c00-bca3-11ea-8c71-5a230fb96331.png)

**Comment by ppoelzl** [comment]
These item crafts are fixed as of game patch 3.11.1.

**Comment by evolite** [comment]
But they are still in the game, selling for the new versions of them does not fix the name sadly
