### ISSUE TITLE
Update Check Failed! 

### ISSUE THREAD

**Issue by HadesGreen** [PathOfBuildingCommunity/PathOfBuilding#1593]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?** I downloaded the newest version of POB Community Fork Version 1.4.170.14
* **What were you trying to do?** Im just trying to run POB normally and import builds. 
* **What steps will reproduce the bug?** Launching POB Community Fork 
* **Does it reproduce every time? If not, why so?** Yes every time I launch POB I get "Update Check Failed - Couldn't download version manifest. Reason: Couldn't resolve proxy name Check your internet connectivity." 
* **Additional information:** I am not using any type of proxy and my internet is working normally. I have also tried running the program in Administrative mode and it did not work. I do not have any security programs other than the standard Windows Defender.

**Comment by ppoelzl** [comment]
Please try out the new 1.4.170.14 release I've just published to see if it fixes your issue.

**Comment by HadesGreen** [comment]
I am still getting the same problem. I redownloaded the new version, and extracted the  PathOfBuilding -master file to my POE folder. Every time I try to import a pastebin file that works for other people it says "Couldn't resolve proxy name".

**Comment by ppoelzl** [comment]
Try importing the contents of the pastebin directly. If that works, pastebin.com might be blocked by your internet provider.

**Comment by HadesGreen** [comment]
I tried and that didnt work either. I'm still getting the Update Check Failed notification when I launch POB Community. It says that it is not connected.

**Comment by ppoelzl** [comment]
Could you post your OS version and build and possibly also your hardware specs?

**Comment by HadesGreen** [comment]
Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Core i7 7700 @ 3.60GHz	43 °C
	Kaby Lake 14nm Technology
RAM
	32.0GB
Motherboard
	ASUSTeK COMPUTER INC. ROG MAXIMUS XI HERO (WI-FI) (LGA1151)	36 °C
Graphics
	ASUS VS238 (1920x1080@60Hz)
	VG278 (1920x1080@144Hz)
	4095MB NVIDIA GeForce GTX 1070 Ti (EVGA)	55 °C
Storage
	931GB Samsung SSD 860 EVO M.2 1TB (SATA (SSD))	49 °C
	931GB Western Digital WDC WD1003FZEX-00MK2A0 (SATA )	31 °C
Optical Drives
	ASUS DRW-24B1ST j
Audio
	VB-Audio VoiceMeeter VAIO

**Comment by ppoelzl** [comment]
Which build of WIndows 10 Pro?

**Comment by HadesGreen** [comment]
Windows 10 Pro 64-bit
Version: 1909 
OS build 18363.1082

**Comment by ppoelzl** [comment]
Try upgrading to version 2004 and see if this helps. I don't think I'm able to reproduce your configuration. Sorry!

**Comment by Wires77** [comment]
Is it possible your proxy settings in the PoB options are misconfigured?  I put a random non-website in there and got a similar error

**Comment by HadesGreen** [comment]
I'm not using a proxy so the only settings that are in place are the defualt ones.

**Comment by Wires77** [comment]
Will you send me your Settings.xml and I'll see if I can reproduce it that way.  You might be able to attach it here, otherwise put it in a pastebin

**Comment by HadesGreen** [comment]
It wont let me share the .xml document but here is what it says. Also i updated my pc the 2004 version and it did not fix the issue. 

<?xml version="1.0" encoding="UTF-8"?>

-<PathOfBuilding>


-<Mode mode="BUILD">

<Arg string="C:\Users\JJ\Documents\My Games\Path of Exile/Builds/Cyclone Ice Nova.xml"/>

<Arg string="Cyclone Ice Nova"/>

</Mode>


-<Accounts lastRealm="PC" lastAccountName="Balormage">

<Account accountName="HadesGreen"/>

<Account accountName="Balormage"/>

<Account accountName="pdiftw"/>

<Account accountName="CuteDog_"/>

</Accounts>

<SharedItems/>

<Misc buildSortMode="NAME" nodePowerTheme="RED/BLUE" showThousandsSidebar="false" showThousandsCalcs="false"/>

</PathOfBuilding>

**Comment by HadesGreen** [comment]
It wont let me share the .xml document but here is what it says. Also i updated my pc the 2004 version and it did not fix the issue.
<?xml version="1.0" encoding="UTF-8"?>
<PathOfBuilding>
	<Mode mode="BUILD">
		<Arg string="C:\Users\JJ\Documents\My Games\Path of Exile/Builds/Cyclone Ice Nova.xml"/>
		<Arg string="Cyclone Ice Nova"/>
	</Mode>
	<Accounts lastAccountName="Balormage" lastRealm="PC">
		<Account accountName="HadesGreen"/>
		<Account accountName="Balormage"/>
		<Account accountName="pdiftw"/>
		<Account accountName="CuteDog_"/>
	</Accounts>
	<SharedItems/>
	<Misc showThousandsCalcs="false" showThousandsSidebar="false" nodePowerTheme="RED/BLUE" buildSortMode="NAME"/>
</PathOfBuilding>

**Comment by HadesGreen** [comment]
[Settings.txt](https://github.com/PathOfBuildingCommunity/PathOfBuilding/files/5322490/Settings.txt)

**Comment by HadesGreen** [comment]
This is my settings.xml file.

-JJ

**Comment by HadesGreen** [comment]
I got it to work. I just downloaded the zip file and then opened the .exe file from there and it worked. Downloading the .exe file by itself was not working.

**Comment by HadesGreen** [comment]
Nevermind its not fixed. Everytime i launch the app now it starts a new
version. So it is not saving any of my information even though i have saved
it.
