### ISSUE TITLE
PoB just just closes when I launch it and causes my whole system to freeze on administrator mode, and then also closes.

### ISSUE THREAD

**Issue by Cronirion** [PathOfBuildingCommunity/PathOfBuilding#2570]
Thank you for reporting an issue.

Before reporting a bug, **please make sure that you are running the latest version.**
You can get the latest version number from `CHANGELOG.md`

Please try to fill in as much of the template below as you're able.

* **What happened?**
* It is my first time using PoB and I both downloaded the exe and the zip version, both of them close after I launch the program and also cause my whole system to freeze when I try administrator mode.
* **What were you trying to do?**
* Launch the program
* **What steps will reproduce the bug?**
* Launching the program
* **Does it reproduce every time?**
* Yes
* **Provide a build code:**
* I don't know how to do this
* **Screenshots:**
* It just closes, can't take a screenshot of that (i recorded it)
If you receive an error or experience graphical bugs, include one or multiple screenshots. GIFs or short videos are also okay, if the bug cannot be displayed in a still image.

https://user-images.githubusercontent.com/82677699/115075408-05ed8780-9ec9-11eb-8721-8340574169d5.mp4

**Comment by lTheJester** [comment]
I'm having the same issue. My PoB just crashes and close when i open it.

**Comment by lTheJester** [comment]
So i just fixed my problem switching my GPU Workload from Compute to Graphics.

POB working just fine now

**Comment by Cronirion** [comment]
Updated the drivers and... I'm still getting this problem.
Maybe it has to do with amd, made me remember how I got tons and tons of bugs when playing witcher 3 and the only reason seemed to be that I had AMD things.

**Comment by lTheJester** [comment]
I have the AMD driver up to date too, but I just switched this.
Settings - > graphics - -> advanced - > GPU Workload
And see if it's in compute mode and switch it to Graphics

**Comment by Cronirion** [comment]
Well, now it's working. Thanks.

**Comment by Cronirion** [comment]
although, everytime I change it to graphics, my task bar stops working

**Comment by Soulprayer79** [comment]
@Cronirion 
https://tencomputer.com/start-menu-not-working-windows-100/
