### ISSUE TITLE
Error after skill tree import

### ISSUE THREAD

**Issue by bigandrew88** [PathOfBuildingCommunity/PathOfBuilding#3681]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

I imported a skill tree and got an lua error message.

### What is the actual behaviour/value?

After i imported a tree, i got a Error message for "OnFrame": Classes/PassiveTreeView:lua:917: attempt to index a nil value

### How to reproduce the issue

import tree: https://www.pathofexile.com/passive-skill-tree/3.16.0/AAAABgUBPpuhWfNo8oKbHRTmfRZv7DjxbNgkOlgulPfXrJgpi2aeogCGd2VyNPeD21XGpwiu_zrYFy_vIRJpm26Eg8Bmj0YgBqHHCwxV1vrSiG-LjHF5MPiApCcv8B-79jwFeuZk53GF34aAMONqM2zauQSzkFX53SzxGjjvfLhdFxwABYXCoccE4wsM2AyIbxhILPGGT7hd

### Build code

```shell
https://pastebin.com/qghDq3Xh
```

### Screenshots

![image](https://user-images.githubusercontent.com/64916629/139565591-caa36df6-46d7-4892-bf11-89b3a00bd081.png)

**Comment by LocalIdentity** [comment]
Fixed in 2.13.0

**Comment by randomflyingtaco** [comment]
Still encountering this in 2.13.0
Steps to replicate:
Go to https://www.pathofexile.com/passive-skill-tree
Create any passive tree with any mastery allocated
Copy URL and Import Tree in PoB
Hover over any allocated mastery
Get this same error message
