### ISSUE TITLE
Noxious Catalyst and Chaos Resistance

### ISSUE THREAD

**Issue by Paroxian** [PathOfBuildingCommunity/PathOfBuilding#4482]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### What is the expected behaviour/value?

When I use a noxious catalyst in Path of Exile, specifically for the 'Ming's Heart' unique ring, where there is an implicit chaos resistance, suffix chaos resistance, and a "Gain 20% of Physical damage as Extra Chaos Damage" modifier, the 20% quality increases JUST the last line, the "Gain as Extra Chaos" line.

### What is the actual behaviour/value?

In Path of Building however, the Noxious Catalyst also increases the implicit and suffix chaos resistance modifiers on top of the "Gain as Extra Chaos modifier" that is on the ring.

### How to reproduce the issue

Use Ming's heart, or any other chaos attack modifier and chaos resistance modifier ring
Use noxious catalysts
see that both the chaos resistance modifier AND the chaos attack modifier both increase in value with the catalyst

### Character build code

```shell
eNrVPWtz20iOn9e_guWqvUoqskM2375kr-RnvGMnjuUkM_MlRUstmROKdEjKjmdK__2Abj6a75bi2bqb1CQSiQYaj0YDDZB68z8_loHyQOPEj8K3u9q-uqvQcBrN_HDxdvfTzemes_s__9p5c-Wldx_mhys_wDv_2vnHG_ZZCegDDd7uuuauknrxgqafc1T6V0B174XpHY3CS--PKD6LZm9330ch3VVuvXDmp_m3aeAlyXtvSd_uTu68WfS4q3jJlIazI-GGdxuldBXvKkvPDyfR9BtNz-JodQ-T3lUefPp4Gc0A7vzy6sP1jUDZD0XKMPN_vLkKvCcaT1IvVRL46-3uGATgLeg7PwVUXrACPJbpqPq-qmm6bZoa2X3dPnJyT-msGET2Hd3sAr2Jvfubuzh6BAHe-EtajFL3dZPYum45lmrZKulDcBRFAQgoFEiattE14iqmJ_M5nab-Az2K_fTozgunJWHN2O-c7Rbgl6sg9e8Dn8blkO4RN1HqBcdXkxLWsUDS-6ZuE8M1nf5xUakptZP7yE-isELC0nXT2rdMzepWaTbMW4JFlCM117Rtdd9yXNt1Bye3MdGjVRCAXYjjOvk6ipa3fkhn44dFSYRYmmnr-zZYrG12GsQ4pt6HObeJa2_mr5LSkPSuQZde6B1FiYTEL_w5rUBqxO6CPZnI4bwGNchB4jyvaAyOI5Wf7kYDMgoTOo3AOW1CY5MhAh_bEdti5MlkmwFbEJqkgnfQOhfSNf1egTQ7_cgx_SGA6T0Iq5CdCM9DKfsFhBVIXeue4UOUwp44LBzmPk7eXQn0XZNY-y5xNWL0-Pm7p8SfesGl98Nfrpawj91432hJ0CSGbu4T1wDnYBl2t_ks7tIQ3FAXHkJs1953Td21DM3tnM6pH9OfRHEE29zPorjzouQnceCCKsYYhmn3xAHTA4Q-D6eC9sw-xJ_CmCY0fhACiD4SOOQaVhrGKrcBlR5TkslWbDk_Ve0nthAkBmT2e-lcUDq9O4PgDMiIkVSvnyug7O65MNkisCjbXqwtknU1uQENGfVui1URaWS_F3pjCX3x4pmEKw5pvHia3Pk02BA6M6enI-9ewnOjGsTRFVM35eiJ4pKa4sYyO3nwEtHZ6rAKtX6e-IgKO4bVqUgaUApDZrQWHjvdEWUc_YFBeLDhuHG8jFaxyAnp54QPEBlx3aE9gwe613S2mlY2KbdbwnlKcQnGs4TFwpIgSL-EsL973zwMIHeriaDbTwLqIGgb0jm7cZp602_H0WxBZYcwIpuPmKzu78FtoO3UVer2bY3XNPGFUMm2h4E_wCoVFylkI307pzSFEngDCkWYIE2mNmITbnATl2enhK7TIFanMk8h95JKvK6iR0B6h-ccZd6ky0BDGDI84DSm4Z9PdfyGFLhIwOj2q7NVjIYqzUN9RJOPN6_ZQRB-Ol_eR3HKLh55wTRhKM_D-1WqhOwMZ-kn06-3q_kcj2p2gUTMTplOTk9Pjm7OP59ksxCHJN_8IPgarpa3eKrA_8UTHw45ocxnKdMoCLz7hM7e7oZ-sKv48GGCIyfgrKepBDRsLVnGPwwLu_I09kF8w6B4TiExVXaINAyHhywSYKAHL6CyIrp5uqeo8UROSpmnG4Y9DOSY4sctMmwtQj-VoXxMp96TBFwRWkjAngR07Ae42cnI6RIMne-SMtCwY8X-7SqVsiiWkUjMAGNrCbbE0FHK8mXAsrhFgnwWqw1DZluAjNlBrCCpomM6p2DMUguZOQeeQ3K3l7u4N2wVJUoCvu-MLpPDJ9hLTlGg5Ukd212WXgrmRpcXeGR-E6FH9aYpjS_4EfrcCxJ0iiKat7tpvIKLMzr3VgFe_7jyAj99wk1KuJqhYLNN7qJHjEw4HlzdCWjk4oLfGQdphgKJ5FQ5-8gHO10fs-iOfWdcsiN2P5wGqxnkt9l2Wcw48G6R-K6ywOP4o2gVptlUaIiJ6iznIgkijP-i2ZOSR7Y1akgI5_KPNzC7bPhZEN16AclQZvUGiIMrt7WCBqI5n_Hw9shLphBv47n5rvKds33OHAQTXAZ95cUp43BBl3j3kqbezEu91-cpiOg1yuk1mx186sLK9FFnN0deynDKhQOfcHfDkB2cMPWTpT9VOD426NIPWQllslouIzCfK_C5qZcsuZ0OC0cdEk5mH0hyHM6AHM2Pu9uk1CeX0tA6cbXJpk0QiEHxwpmCOBRxN35ejssSyk8x20Ajy-d49oBb6IxpPHluDotdanvuPoW3MO1ZA5Msg9l4pbphPh-LnyN_Bvubf78KPJ6y_tzaLhjvRCzLOSJQKhiemXXc_dMubybFYx2DLGv5OL5Vcoc4uG3w7fPZNo4IjXHjLYPJECJcLCPlfEnL_eRH4oWLlR96KX2mPaQVpawaqoP_o7sFBCz-zzjN6nhZhvmo52YlWCUQeXUHBnIMtWCRZouP_Xv2gP8v-_pPuhEuG-5ExqvYS4Y9yXbOg6-wWjwsrZR3NPaC2Yf5eBGFT02MDJlwEbUwoVyIgtYgcKcxrnqygcupkS4UR-Q0x4cr0Vxpzr3G1-Ten9H4Cna9POl_BnM-gwRpC9vN_Gx1tKy18lHPxQHM18dg79ALQzzA2pKVDjSyPOXDlWz883EHNrnEvagzCpNirg2LPG_i6Od2K1dxNJ364UL54qd3KPmNHQwCPVNKOwmySTxLGMI5At4mKd18_ypGK2z4c8v9b_DkGydSsKMcw__PmmEc-w-wCR4GWDUKF5sbOxuuFOP_k9nFFtw-S67xHH6KxRxYEcK-S1SszI67_dJqo7ehCC494C4KKKsqtob519S7z33537vykmgVT7G1Fjg90PSD9_RRwc8j5TO63iDAQ9NrZs-tiRveUsjP-EZteCdK7j1famdkeEtB_19wXcNyeMYw9GoVg4A64tANt_A6zlbpZ9l-f4DZMiuIeX_4yQkgpJMomPk0zsmxcvKQd3gGkcG4FKKLW3bu8Bzyyh0EX8MV9JuKjqNQuqYoTh6L_HUzzz6xAsZNTKnicYNkuLWsIABfxEZ85EpH88XM9Smrb73d_ctUbdMembZqG-vRX8R1XX2k2Y5J4JthmIY6Iqrl4j1LJZo60ixiMUjHVfWRZWTfXDIybPgGnzWiO2Skaw5hOIhuaSNTdXUdvpnwxRzphu7oaxBINMP6hmYZzkhTHeKODM1y3BGnZGqEAHXLMKyR7jqaMSK2ZVojwzJtBzBqzkh3XPgbJwFIiepqAGI7gAy40keuY9s4Eujr8I870hxLN0ca0Qx9RIgNVC3T0YEG44VoDtzN5qurGnBHHF2D2RggBQMmCJ8NxwDedNsEeMcEeKLruoF4VJyTY48sy9FBGMQAIoZJbDIipmo6I8fCCYBURqalaRYOIcYIH1QACMNwrZEGsgfmCXA_0lWiAk-qhoJgQssU5RDQj2PoIAemHU23NaSvWTYQIhZyowNPgB6GGqYJ-sQpsTmCsDRXMwy8AnxYtgvzNXVnhExbeJVPDKB1ELY-Mk3DMVEayLWBVywX0RLV0OBvV4XxGoIbrgtK0XXUEtiCbjnAMuB3wXwcjV0AZWggABCiBjSRGKjXtIhrjhwX5gAoVJg9duoz4VjIp0pG3J6Irblwl9mnqWuMZ6YdXXMNgHFUbeTqJkzWtVQLJm7a2sjWQE6ahbIxQIEoORvVQGzAa5kqTBxEDyqCCQBysAPQmQHSAiODL2CCtgMIDLAIQgwwLLiMNqXpJjBmg4iAJdcB9kFRaLDAKXEcuKnBmlHR7FScrmFau0oKK1V4wEZzsmdncGVa2RZyMgOHOXuP6yLzkJ-uL9iHf9yl6X1y8Pr14-Pj_r2X3kVz-sMP6P40Wr6-BzTgAPaYD9lDQq_H8N_h4rfj6fj3x1--EZ_Q5Onp8Dq8uV-d3Y59zbn74C3Ht_bRr9rt7fmjZUy8z0v7y8mPifvw5f2PR1P7fHH_a3h1Ov_8YB_6CzrXflm4wcNMS5Yn7l7wZB__9hs9P_790_SM_HnjJ6d7jzf06un611_d2e_29a3z--lp7J4f_qI773-_2PuD_JLcfv_-dPYpPj-L1N_94Md4_vXht4ep83TnJN7X7x_Ne_MBNo1L6_jq_PDf51-ts8i9vvn3-P2Ff_WozR7C81V8ZJ9Nvl_vnT_-uozIbBJe0Ydb73Jx8s3f--MLub68NY6dMD6Z_fvTzRn9urifL48u_C9fiKpO7385vP38K7m4OaWh-_2PI_vjsfVwfvwOPvhPJ7fu8cfjjyfL8fX49GR8shhfn5-eLE68w-vodDw--X748ePh-eIkPLrZO7f-vLCP3h2HPx6-BPS336_UL1-pk_x--um9l369iLzx5Nq5-eOQXt_-0H75-PYtU-TrXJNv-PNPCVdr9o35QmYJuJwgTEn5RpR1SzXhmA8q4UgXHPNzJZymdiMEFykAdlJm3qcEdLvg0FNITJA5GoFuHhq8FsQEX2A7Yzsf7nf44X2UUnYPL-Zf2G742YcQN6FePL2bpDHGdH9G0fI3oGS6-6qpIUHbcHlJ_R310kvvPgs7EDArx1tZMT710mMfdsuYNRvkUQYC_vp2d89x1H3dwr0IdhmDN8K9YTFDtieL6ckqofxhiy8Q_UMEQdMyemSDWLNClgpfexhTHSjX4-uTnTxo37nARi4lP3_-N32kwc5R7M3BaRwoOLWdq5jO_R8Hyl-xFy7ogbpvrsfzeeCz7giQEwYnh16aBvSdF88o5CJfpcZcssAhvaOnq3DmYWkQwpuvO5PVfHDoWewvP4DHKoDxYb6dChMKC2gOFK8Y-_U-a3H9OmMJWQ0eXaTCwvQDxdnJuiIOFHWHqe-afj9QTGPnfHkP6Pw0OVD0nb-mXFDr8WyWKI5yxZ0mJ52Ut4kCAHRWu694Mc3nyg2zghDgJ0sPUo_aqAXIBaaokX9i5hFTL0HMGWvZefqO1kZR8ROFK2ov11Q3IIpYYTLuBOEKVECDiqhCtrrQtqpWSPqs8JLO_NXyp80QFoAXzk4jfPJUzgjPVjQGdrwbXFzTpGpQG1lXGnv3X4H616Uf0mETM9tNzFD7TMzsNLFOJXkVE9vewljZJrOuTccKlZ4eg8s0oeSq6IQELbMCEtdzi7k9gI15mCIR3q2lV03v0_vzj59Odo4phE5gsN9ozD9_80OFVZV3ska0A4W4Rv7lEFjJngaBIAlY3PnMyRwoYGgK2bf21fLS0SoG_57u8I5T4KK4Q-rECjsg6k7mCA6Usz32R7AMQkTLyEEB8xnbG2AK2UkbXLp94lmtomlMcTvZEtDWLzRL3YPY5aWon4xD5dpL_XCxU6wXx3bWr17o5p5hvlTSCFI99vSUggdyIkpjT3NeNowlf7hZYf2sO39lWjkga82sWEf22EAdTlvrajecMo9ixYVdGbe_RIHZF_S8jGc5gsOIMHa4jGbXyK_CuOYdcEIM0rjPhJdbXwdMhiPvz27xmUbvzo0qu6JBWpqr45pd5qruu65Bhnwq5ELr81xQqGa7CQPpzfoigs2mAMxIcvPJiFrFwIorLX2xbax58_BNlD85wR6jSIweJyy5Vmy1ulZeac4_lSmjhnac01MYwdwzOWbPmnhlu80VkHqL5GAVPlCQMPj9aDbyeI_T-q8p-P1ouRbXnQarpLru8noCK6lm3VHKU7QCELatKI93gBn8HGCDlbGdDZmtzg8PgZTzGC0o8sFPnfwZLZ9S9NKLBfjDVjkf7sEfQcpWxSNpO9Xlyk_RFGxSZ5EJRM7-N9j-mBZ2XukoToYLuWc7SR7DcK1wd4_ODRwmXA0j5SSgPMbIVdbOsdW3agDHApyCcs160nir8w7vP4X9ltjZ58byKRcZAnUtsqH1pZH62uHkxmG-iIy2BcfHILU6ODdPvSXWcd3qSnaaa9BSrXX2ROw4CHhPNWlZqi7pWKrv_MWd8VV2iXYuUC1bSrfYrL3WSMWOWAe3kj-aCIajDi_lV7qNN7mw8m-1FW3aIhUOysKKDG7nlWM2lvwriGvgmscqAvw6FxvOpyvytfvs8QhXSdob8TKxtnrTHgdZ94C6qrKps4Vfzrm8UTyU1XoXnz1rvcGesRLv9IRjWhaPOa0uaYIhEfgCzCcuongGwbgPLADZ6JaC7XiLFSyxQ1DY9K4MtMbTGCTIAsbyGioD4vEAIqxwJlyPYWMHGwmxhi9cfvBSL0bSyGV5HSwvwv7NhT8VAjvUPbctgeIR0Fn5qXAB0qcEjO2YyaS4nFVsM7dTXobkP5l5T-WVk2AGwpnesYQN7V64kzvBk-8rP_BvY8ic2m5jwTGIPIHMCesZCpTfolUqiPDsLkrS-kz5xWvqARbhasCFh7J5FPg_X4IV8zbmsxXklsId3GMgmbyvXbqm84D-oEnt8hdw-uWlC4rGgC8BEmYGCqG3Xihe8WHZIrtwD6VVuYNL_jwE47z1cWUIUbsH9jZO01XIJCbcoDHWMniXk3D5DjxFq72xLRRE4oXfKknB1IcBN3R6F_rfV8J8YbVEwSptvwfTuQV-RC4mUeDfwwIT1Ax-L4ZpK_hw04xWNJffOllE5cUbkON4EYJORWPGq_zxMIHap_ARlc6bOapG8dnzMOObCsLC82cPdz8Fn26BhSRK8osP_n-mfKlYxBfUFrM2gejvsMVH6X9591Hy3wk_d2imThqpuATB19VjQYhUrtvSpUSZemEYpcotVSBe8-c-xFWvSCUWqSRWO5raFtXkjwrtwFJClJA2BE_ZSBBEHK_ui9QMrCy9g7QVzyPF7EawJCFVqfmu4o6-rnqv4oaxrvmv4o65Fj1YcdlaV3xYcd1e516suOSsq36suOGuq56sZEtdF86svKitG_6svEnW7S6thNDXLV6tvG2sq46tvGOuRd9WXrfWFfdW3rDXNQ9X3nLWDSdX3oRYq_BzpTLVddXVlXe0dentyqtkLTq88rq-LnxeedFYN9xeedNct3i-8ra1rju_8p69rvq_8o6zbrjA8qa7Fr1gabbquukIy7vausUXlrfJWnCH5WV9XXrE8qqxbjrF8q65Fv1ied1aV1xjecNei96xvO6smw6yvOuuSx9ZLlF13eYmy_vaWvSU5XWyFp1leV1ft_jLwu10hKHuT4ahRS6bZTyV7IIPHEj5YakzOBYzAkyW81b7o8rXxpHO0LZMJOphri0EpRyvgnmDgpiVEvVOJfivhPjtwtPUPunxo9CfPb1mT9eDVYGFgFpXsXTQP3Q07fE8qPswmsjUO0jtMJp0HkZLnA-bzeSr-8A3F4xSSqZDS72lruPYA4-WQCZNlTMPGA-w5pLn_oRYw7k_sZytc39TtYfy-Jbk33LLQRVYGIv2SppDdJPUD_FaimrtGb3-84dvll0_fDMlMnarkrFrKmlJ2eGy2kjJe_JNczf_PA5SzMO5kZD2EzE_noJhQBT1PsKywML3dsZL2I-fMFBA8nkKOnnCd4nC7iPE3MxUr9lLo_iR3gssCuj7mravvuyFyyoFApDovYRsFFSh8C6rDuQViCZatp030Dby92bYbdbk8M5LFBBoCcDsvRhXuWWL7oS0HfpMcQKjP9AnwUb79DUuplKenr56odl7RH_ZfuLA8ZQYvPwFCuu_5vhMPfiL2VqwfMCGNZCX-UlO-cIFcUriCObvXmhmPuoF0fZ0-FjR1LOxU6YIwhRqD98oEIkpLyx1r3akjC96qNgX2AMIHIIhMZIbRKyre8YGiEWplQmLQOSFoe5ZVYSVPZofdHvMdnn9qjYtMd8Zmryt7mm1CpewNMT8qNBIK57mnFvRWBVLYcNhJ3gE7SsziNLaJyRtM2V2VrFgXdszOgxIQpg9lQStu6JlDta8zI0qXj0YzEEIaxDCHoRwBubpDmIomp96QLTu2oym98UrtXb6nXcQsoBR8Xi9P9bAk_2hOh6BLLG9hDdUu9NtfQ37S0I_hPiiJN5sfx7OgxUmXUTueLrcF5zWYgAsAvagwSiA6QuFNHPPftkZvL_SiNMWONjNo3zGAISWdOnTRHn00zsl4wRrwMDXiF_UK60M2eIfXkCt6u6t537GJ7kh_1MOsaY7pGCL1Ms7zYDTEEpAHe_361W4fK1BqOw4bcrkGciIcrWMZtnxmbglEtjM9Gx_bVZjCk3qlikGio7VEhBupRuzTzfjhZdSZbxcQcowpBpbJ11rr7uSUwiCHzB2pcTanbmpQiyzVSFljCREJdYeMZgCJikEjwuwflTBObgdcEMLdqLyilhs1-lLrl_Z9jNopQjj9QzMao3bL8Es8nOQd9SL01q0euRBMA_fUEY__GiVFFfEfKavl4cH26pce4_eSBoKRbh_Z_jLvWQZOmLSFeMqr7vINnCy1tQNwMvQDt2xhpFNz9iSN7bsk0G6_C1kxdHyEBKJ2bRhlBM8xICm2it4jifvLRWjNHyXnILFbHygqdqgqUB8efIjjb1qCrFVXDYUUw3ES9qG0VJ3ddeqpttGHgDZ4nWCQZPWupK_4BvRaJwv5pMn9JV-ssSj5uxQTSjxLmh8wMvSmUjR5BT2Er92sCsa0pQ33DQAwF-zTpW8SwWdWSuQQLBxH3WcHWGNk1otWQQ5ikLwmug1bqIa2FGQiSTjib1hTjmNoyVPwA7pPIo5q0OD0Pr4THBkCzRDWEz3ZFKcKpDKqUInfBdI3qqBWzaVQloZ0QKU3efAH8LsFOVT0g472-eA-AMEOXmnnXoNGDZR1p8UoksQy_PiSwUOUAY-foLVnIUhEpCsjaUTkNlFpr4iNuuEZtPm7iMbwywEDTjpH8RKUWzDEih2DvkUFknk4ZPyeRWE-K75Whn92E-muO-HtMIvP92rcy3AgsFdgU7fiV0TtfsyltQ3pAcKgpn2u6e8qX2SQiShfJgjQvauW6EHAl8JUuGVH6XiamYv9G6AHgZYxclTjS93NKyynYGVaNjLpxv30f_UmmXrIFWNnYRzSm8DAdM75K5BiSsraYJl77QrpXoaxcIU-LF_fdQxxXf64v52j86SC7QBxTbHD2ESeKvFXYqr-pdK64cIhmXHSsdOdrPK7Q3FFw5zdfhhZV4Qzc4OMt_FGqDqhi-AFEoVtoOsabEBznC17is5BNtY-ig2dwQEF7tdiif_Cwf_oRJ0t_u44XEdsGwbHaO9yi1AucEd8FUNsncEVxTdA8xfFNwB-humj0VLLesfzT1lzRx5dZq5uyPeGnJI-YIVl5cAdRp4yTeFvwAbzRbtpBUQVc_fPt9QfjtUbUnXgOrhSYc6BkaJgP6sdAW4sI-jFTiLlsmKgGCgvCbeAOCXxSX0rrIf5WAwq9bNp7if-kt_hgb3oeYn-VsB0Ctn_SBJS_2iF7q2CZ60sdsyDCOqLLxLautzELwa4A2CF22Y_WNqjh74-EK9byFNkrZxOAdU0HIVcg2yd2d3Q0oxwEFrK3gVsxZS_Cm-cCY7CpbUctnszyvGnE8rsz-NKf2TdgJWJn8-7QasTuLozseor2fqLYMg7krS2w5ZFqoUJz-5q0RErdDyBiEMqnGDrVz4vGiHSDsHsvm1iOGzn2anJY10q8MT9YxoAwIjSDkIi84GkTJQHh7Uw8gaUBm9YJTM_HcyDNyz5fUNaYPK2gQE7oRuSIgc7pq-uh5xCGBlo3bddWVAdQDcjGti74JkuVBFqdWoojGuNfjJoKr5cIsdi3CVEKgFljc8xU-4TSeN8Fe4G4UJncZeWthwXhK_8DEHT3gMCxObY5x_Qb0H5IM1gcXUk0UJsfxTJd9uHdhQqDJeYGyaFskABhAN9AO4kkLq8BFdv_gIQstQtkjG8dTDfs0Vhi0oAkOZZI-8sYQEG1mPQAAplZzQZX62xvM4jgyVJ9zglsSWRUs3r9U43tmks8Aw6-DKzWPUM4Tf1lRt5wICDLyZ4vdqs0qlZr1ntVaaaqeJEiPEByZ7AdlRTXsDwAttT9s3X_4z7_MtvCrKGFB4CfcvzeovO3vqqP5nSASDwuYIDenUHvkYRqzXStTC0WntIbCyVjCM1RjoIxBlMYjMbJzPsq6OTKydh7Qb0aj0A7wgJu-kaEFfurz8ARtZEpVmgBcWP_QGCtn4lB0AzotTw9vy1LAFd3YaJnZ9V8yOdb000XciYvvh6p6bZNWg3RbxE_7wMKC_FBZBKfvLtlUnw4amNqmVonpuYtW1SlTsD2rpnxGDCxm0pKqLbGn-NFq9FW3ZpJefuGpqJiyg8ojbBD6dukoAfXYIK0OssoL3kBp_nJz9vKlw_IrPXvAuURmslaX8Pgr38pNb1pfN8dx5D1TpoShDR1jOjmWBX7NU1s5TqVQ3EVWOUitPGFScpLmHxn9UCJ4_7Vg5NtgAeXXlctxemY_XHVBx0rwBCXeNkQK6gLJBKi-3VY6k5_mRtOD4E3lCRK37fVMkVT3IFpnq8k5ddLS1kADd1o65N8BDZBQr9ry24S4OoitPf1QQc9dS81ALXuzBVxng45FZfApJkSwRY8B9VckNOZxWEuaAK3sGEpWtlyVaNGZpHEROeySPnqqE7svgVZJKdffNWyXnvHCQsMJBg0peRpCl4bRZU-mfWZ0hdxN4zNaCl5UEKk_o1KbNFtRUsFCxSgH4wI7QgtDlD2LX1VqHLalvKa193xKItaEdsPo2j2GEpLbg8yqJxFC9XyuyLLLyReXJpTbNCK2yjToMWxS4MVdrMbg1zyQIQtyfFWkivqVTXqspgr3MmIcxWWw7WFSLOXOWXgpvVPmlPVSoI7MZMrZpZyUfiUGVlVLVbK0iJIHMbXZ9m86enXV9Ow5s_MZLsaDTihMrO5Wnv6pLYx_Wxr7TnhllG4YEVk0yjas98C-Dmgy1bm_Gv75VQrQhEaOWfFp7hvFyqFOtBbFQRhKwC3uXDaRAic4eIc-H32pNuUqJFws_zhY-y-W8cDaYqbTTq25hYNbkbyXn1BZmXuiTRuDWEPDin-xwU22sFSTe-sqdmVArLNZQpztsJ6etj4qnzLNSYsvYolInjCQ8T_WqVcYi82KT8xpOQw730AMZQ0lHG05jYHMWK5uSKM3nOUVqQ221RdLPg7p1QZWRAbcqsb6a4V2xXY6VPgVszppUnpnLSqt5bMb703l7Opdw0ovOXXMEVUsP8BydiPmhEEi2IrLUAROqO_Q-XNqaFekZTaHmm_NYjSE4Ipw9vuiuHSHpNpzhJ2SyylhU1lgFzLpkKlp_P1VnLtpLzWgzpZbdkiXYTHycjJcM7Jm9VM3tqfYfXfZStban2qhdbUjarqcBhfLySvqmGPENEazMm-YV9l4M1Zd1WG7Hme4zKqBK0Vbru3KleL8JpvoZiljQ3wQPESTIq_y9o8_FXdfWtxeg7LqpEjRqXFc7CDZAVM9biq6CDXBYguhYDb93bFlgLTHY28tvo7XYRrseIIrtCxsjqweL1ZaGTdE5alcVLuM1GCzA5Z0AAtLqqYa6D65vn_w8WtJ5AIaH1pB3cVy9Z14taNuPIBmqTU4eWzBXNztTxVxbjCiqDRbzsoFDDr05cKzZ0vIhhdcaiHu3xWt36q80u0KDyQYarFYGWh5Ilj6IYE0bAmZ3ICaU8A01lG7nimvg8hOx_j2UnNbpaFvSycphQ-hlC-1tb16UQK9vV8veQh_GVgc4WxAaKhGUrT8tyPLWFAGftc5-lggn29LGgwnFlDe9dOPLGoeYiyN5RiIQqazZrYlMvVUCRkGz9Afkx2tsDt-Hm28OKOjXyvXo6InU2vZqvUhRWy-SnKArTqBR9CuMvmCH10eWYtQtNDFJ0QRG183OpnramB2cTLs6myRJNd5FnvUJpKyg3FG5Enw027h4N1QPwf73CPydL2YoIP7Pv5qhgHjWlzP0gQyLVRuWqzYsWG1YstqwaLVh2Wo9wnUsKwMali8Zli-RsNph4ZFhyZBhyZBhyZBhsyPDctGH5aIPy0WXWM7DotOH7U4fFp0-LDpjmCNjmCNDwkMNc2QM24sxzLTRw7RtGBnQsMUYwxZjDluMOSwZc5gnc1iR5jBH5jBH1jBH1jBHlsRmM8y0Ncy0Ncy0Ncy0PWzg9vB0nWHROcOic4aXiTMsXUdiuhKb-bB0nWHpusNycYedkDusI3dYuu6wdN1h6brD0nWHpes6EpGQRCikSsRCKmm8BGICsSv7Idq3u_xX6BSt_O29TAYi0FkA0XEi_Dyf1oTBNyAJEEYT4h0NllSAaQHJZkNKIKsJlP8YdUFLb5lNNHvKGj1LQKcDl8C8ZrXhYj_Nm4O0UOMvGRKw5DLMfviv80f_xN_6a9PK5NG7V8a3T0ni5T8HppglncJCWobWhxG5YQ07aIpiywm18TIwKbSpDYfwIrwuNSXSNiV9O_HKCYE80zBju0la21GztpemNqDgNnsa0AB3I5sSarEkaxs6A-bX5SklMOvbLyNtG06M7YxB2870jGH9NHePFtFuirfNwLbkXMrzmFvMZwsvqA-RKba_DfXXLuWtDMzcZpDUomzEEC2K2IpPc2uxki30bm23lPTtzFff3MqM7R3_FjatbS18XWZlGjJAW0z7J8IfSU02omFpLVhbWOX2avgJc5F1yThWctXIg24hua4cRMLHkK3lu6W_kFdoI1WSYEeXEFRLgiWtCGNrcZnb7AAyK6aRC0qb-cCUOvPI11kiiT8szz6z37k_isK5v-CJZni_yrFgnsnaQ1m5Lmtm3lVuoyigXpj9eP3r7mGs94YXYXeVcLW8pbGY0gpDlkXLLf7o7k3s4w-R0tk1xVdnBE_CaLVlND7Ngo0RKa7TodlBBn0a0_DPJ95fnWzADxND1ui16bCsv05qfuwnT7AYuvkUs5-LlSJzFT3S-OekIKXcYiT7beUQNfwhxp8FL9W7GfGsp2t4WGlWX_z0Di1qgg3T7IdvyknzU7Y3r_NV8Ob1lZfefZgfrvwAH1T4187_AomvVyo=
```

**Comment by QuickStick123** [comment]
Should be fixed in #4467

**Comment by VitRF** [comment]
This bug is still present in version 2.25.1. Verified today.

**Comment by igloo15** [comment]
I just ran into this issue as well trying to figure out why my in game chaos resistance and in pob resistance didn't match up. I think its because POB says that noxious catalyst improves physical and chaos modifiers but in game it says physical and chaos _damage_ modifiers.

The key word being damage. POB thinks its just general physical and chaos modifiers when its only the damage ones in game.

**Comment by mcd8604** [comment]
So I just learned that Noxious catalyst actually doesn't increase chaos resistance because I assumed PoB was correct. I went ahead and applied it to my ring in game only to find out that it does nothing. Any update on if this will be fixed so others don't have to learn this the hard way?

**Comment by QuickStick123** [comment]
As I said in my previous comment it is fixed in #4467 so whenever that is merged.
