### ISSUE TITLE
Whispering Ice + Winter Orb + Cast While Channeling = Crash

### ISSUE THREAD

**Issue by tylersockington** [PathOfBuildingCommunity/PathOfBuilding#6653]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues)

### Screenshots of crash/graphical issue, version and options menu

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/144697056/da8ff90e-03fb-4808-8d45-bc6ff6d035ab)
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/144697056/26942f33-53ef-4eb3-8c86-10f7a0632428)

### What are your system specifications and configuration?

Operating system: Windows 10
Graphics: AMD Radeon RX 5700 XT
Processor: AMD Ryzen 9 3900X 
RAM: 16gb/3200MHz
Default installation

### How to reproduce the issue

1. Fresh build
2. Add/Equip Whispering Ice in Items
3. Add new Socket Group
4. Add Winter Orb and Cast While Channeling to the new Socket Group
5. Place the Socket Group to be Socketed in Weapon 1 (Whispering Ice)
6. Try to add another support gem to the Socket Group.
Optionally, you can import the build linked in the Character Build Code and try to add a support gem to the Winter Orb Socket Group.

### Character build code

```shell
https://pobb.in/Y5bLRp_FaCWL
```

**Comment by Paliak** [comment]
Fixed by #6560

**Comment by tylersockington** [comment]
With new update installed (v2.34.0) this bug/crash still exists. Below are new screenshots of the two errors I get before PoB crashes. 
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/144697056/3ec6d4ac-5fa7-4b3b-a1e6-f205e6f672cc)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/144697056/0e256617-f625-46b2-a3ba-267a346ef32a)
