### ISSUE TITLE
Multiple support skill gems do not apply to granted skills

### ISSUE THREAD

**Issue by moxaj** [PathOfBuildingCommunity/PathOfBuilding#8138]
### Check version

- [X] I'm running the latest version of Path of Building and I've verified this by checking the [changelog](https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/master/CHANGELOG.md)

### Check for duplicates

- [X] I've checked for duplicate open **and closed** issues by using the search function of the [issue tracker](https://github.com/PathOfBuildingCommunity/PathOfBuilding/issues?q=is%3Aissue)

### Check for support

- [X] I've checked that the behaviour is supposed to be supported. If it isn't please open a feature request instead (Red text is a feature request).

### What platform are you running Path of Building on?

Windows

### What is the behaviour in-game?

This issue applies to multiple granted skills, I'll use `Abberath's Fury` as an example (another granted skill where I noticed this issue is `Lightning Bolt` granted by the new kalguuran enchant `Trigger Level 5 Lightning Bolt when you deal a Critical Strike`).

If you socket `Added Lightning Damage Support` into the unique item `Abberath's Hooves`, the granted skill `Abberath's Fury` gains additional lightning damage.

### What is the behaviour in Path of Building?

In Path of Building, `Added Lightning Damage Support` does not affect this skill in any way. Many other supports also display this behaviour, for instance `Increased Critical Strikes Support` and `Added Chaos Damage Support` (strangely, `Awakened Added Chaos Damage Support` works).

### How to reproduce the issue

1. Equip `Abberath's Hooves`
2. Add `Added Lightning Damage` to the boot slot
3. Observe how the average hit does not increase

### Character build code

```shell
eNqtG2tv2zjyc_0rBAN72MVt4vjZNJfswnkHm7RZO2nvPhW0RNvcUKIqUUm9h_vvN0NSsuyasmS5BVpJnDdnhjMj-fT37z53XmkUMxGcNduHR02HBq7wWDA7az4_XR8cN3__rXH6SOT80_Q8YRxXfmu8O1XXDqevlAPeEeBJEs2o_JzS6n6FZyEJ5JyK4IH8JaIb4Z01P4qANp0JCTwm0zuXkzj-SHx61hy7gNx0SOzSwLtYPjeAcxIRV9LoHvkOEykehAerU8JjWPYJC8bCfaHyJhJJCHI1nVdG3zTQ3cPjp9FTTiYW5GUCpd6dPnKyoNFYEunE8M9Zcwi2ITN6yySQIjwBOoP-4aDZKgQ_T6JYXhIfLkuhjUNKvQyybQN7jOjVdEpdyV7pRcTkxZwE7pJD34ZXFfYh4ZKFnNFoKdOhFeP2B-LoDhbgJyEJv3wclzKLBhZL01vJfmFyfs7BiGVJ380CJukKNDh_f1DE4EecdmdwOChGehQsFkFVjcsLdpFwDiGZR7BaaURjGr0SyVYFssJfCH_CglWjblH5gQTkQsQltgwhH2kEcS4rIYypKyA1VOVREfOeTWl5yEp6GISq0uymx9W4LFxlwrsJNIKcWA5yLBJeElIuE1XfCnVJv2dQnYIY-bYCaM8ggSxHLg_Ybrft4r0KqQ6_beqqJHF1-5iLyV7vsNvtfXjf7w4-WBP143wRM5fwB_Kd-YkPefuJvNAgH9pduwfO5jKARGNDfn_8wYZ7zSK6A9qF4N4uaHMi4h3wMMZKmQIOa_cEoe8Ct1zoPgeRyrz5M77Q1lM6gpDCWmLCaWmcJRsTmmUOZM1sRgPDcVFOpXtK3fkN1FsjImm5RLw80Hq9QtsicCnbIuAG2xbQX8WoYCZE3GymdvuwW4RV0VJXAY1mi_GcUe5Vg04luyBhiZSJhs5jlzL4KrtKTpNHrWiSLyTyyh0sVWV6JXE-4x4Xx7wBL-eaFKpRQPDoWm18ZC_uxV9Y2vNqaMPIF0lUcsM1cCkF0sNCdzEj6iVuudMp61DOObRiZdXIsEBOziuhDqUk7sul8GaljaaYVMJYlW-chCEkEfSGsgTwEIT6m-XqmYNBCehP4MqlIhqPy_IMltClGWQlQHkuayjldcEzvIIyS_DSLLINfYBk4cMpoHrwB5E7og_b1lLqGrquUi2UAlzt5-whJ95A-DmOUeJq0FDuZAjWHHYd0eDvRWn6K-ClGFwFXhJhNJTmsY6xic0T8yGXxvElkcTxTJH8mUSMBLKjRjwxJZE7v4fdvyacTyAZnDXzT_FuDbGdTllOW2qQhVd3figi6dDv-N8jieQiHSwpQPUE6MSSBaqFhszDedMZz8Xb0HtFLZ6E4HE2jSJhSANvhcZTRKlD0jziohBKR7xxfBJLOLa0Y8YodG4KduehGZ1AgADQ5Bwfd7uoIvZdJFoMVwEDBnJJ4JUbxnX6Zs6mKSHbd6fPo3t18W4uZRiftFpvb2-HIZFzMaXf4SQ6dIXfCgEJBD6IXxjnB0i2NYQ_57Oh-qMItVJKp3r-Frf0HYZjxEBmvZctVFRZHS2BFx-FpDGu4cP05nSMrGInho24oX58voD4ucbKYW0mYUyJ0GMqtTPkcc6aMkoo7v6UJByf_5kQznBnO93843s9xwxE5Gf9EdCCrcVUr0k-LUK0_fD-Xq8MuTTUkF-6z3o_jUQO89I9Ng_VjHK4FPuCcDdWgrPA5YkHTYXJLWYbOZmgZKhYAtUq9J2S-iftk-FkAu2BnP-DhCL-V-zcCshj8a_OjYCHYHHnXAgZ4zQXewgvtUTMBdjJrK3Jkon67hQ0Mpg3XEwI76TSaDu9B0KIgb40oiGFeAhmEAjuyxt5BS7fUisfNVfItFMx1qRyRRJIwyIgvgmOdRWvEyjqjGO1lMTbDatIbjNtJRshqt1KmoIxUwfUn1EfrfRAJfEgg7Vw--IWekxr6VpDz6NedlguB8cqVyG6Ad0Ml21FIdS3vOebG0S61EFQaaPaK9uE7JyMn2MY_rBR5hLCQmUAHeN4qbZKQdwFYSIV6bOmz2L36ySZTnF6D0rKSL2TuLq-vrp4uvt8ZY6HPIoyxNcg8Sc4udb_L8fpY6oqWCdOJrG-PGt-ZvRNCXIJ-8N4jBpyTsKYZolbxbCRnANeATUFdcuyyf9mWksAO6Wr7zTCmILWx40YtcqVrW8RSjPEtgiPUxs1HLXbCek6-wJOKd22WSylXmXYqeD7Bas6uFiACyc04VbOZnWLJSRmcfBbNmUuViLFW445X0MV2MV1oYhxFwX7bZoEOw317sJGQC_akfUrBhu2WS2wqnqtYbWqXrWjX1KXWHXXi3bkbBIgAvWKbTOVDKqA0kcRKCeHoBkyjgW9dWevOM1A7AQ_yTmNTDFmo_QAOSoFKQyciE0SaQ_jHESBrdSA0mIhXLOj6vGbRQdcK8hEK_Moi0HzMHZSeo5jTWRFqLq5s9rPtIoFW2CmJBbz69UCI6SDIov-ZrkgSFT-Hb4K5ulxgSVc1sCKEgYUW_XJqBlIfTLrQ5H6FK-hVXmx7rdZtaM_S4b1zQYquo4pRQSDqh4FjK16FJ6gdpVJRHcmMFqvRJa4o-IaJOviNyKnq0WZwzT3O1PQI4id0dWEZGdslf-hOKagQeEBkMEUxIdMgkswhiyIjZKklFibE8lSu0q09FG4UdPKFHWAm3duRTlAg2whBGf5bUG1WI5SNui7pYTj9xiC1yP4w7vFOsTwZUUSksBLyX3aVKMv96Gk9aB1BZpqtHWJ70Tq2jCg_mIDIbtcp620q1NDL-yzzERuLCPsuf8Wwv-PGhDglZm_dM3MBSruSwb7Fil_S_kg4L_TaeKpaqTNBAivswGQnUASU_2pwhdKQhEojLSdV_Ty85oRdN9yceI8f7z78_mqsXne0lgdtzRMJXDiDPrp9TmJ0283GKcnTrthpkYnTueoYcZlJ87NgfrbUJYY0W8A2GlAS8OZy3D9qPEUsdmMRrGjQJz3zqb5iPM2p4Fz9S1hYUi9xn8hAc_oSft___y5c3TQPfrFkcKBHaDBTM4b7f5POBuJKIjoOekg3FEt3BL158FB--iXn_DjOzAmEtA9QeMLslqIxPkD5y8kMM89R7nLr0B6CtJLXKEg0Ct0Z0BdAzngYZS4cycAp5gsNEqjnZcH34GYYYIT0gistZT8PInUrAF2YRpGDCp5NWx4EN4IpXaU7Hqs5mUTAOt6Z8t6d8t6b8t6-g2JGv5kzobzQZtHrg4OuZAO2Mx_nDyP7jF49LjjhqMLNtWSnuq2ihE0E6ddAUW5NXjaIo4Jd7S3Ov0qBCiX6_idCviqwHG6O2jpjN9IuM66twuhGuobGp090Nis0GAPCg32oNBONDYpVNs7u3uwSGdf2lTxt1sKlZisZY8NwTaoLUGnMoXaLLv7sn9_D87Q3kN4tPcgR6-iJ-wrxXTqRmRvDwasfmbsLcV26-rfqRnC1QTwFo4eaNXxQV1b1KGwObD7tSkM9rWt7X3lmOquWd-Ovdp72d-PU1VRfugnnMo9ZMLuHhJKt2ZQ9mrit_dj_51PyspO26uMsUsVVdOq_bq5ek_b0ttXctlbXb1zC1UBb4Q9ead2aursZw_2dlLso-Hr7aZTVePXP-P3VGz0awtS_4gbVE0GS_j2TsnjR4Z65pN-86JmluqTFxFM2cxML_WNmV8qpOzJyhzokROXzgX3aGSEoDg1Mz8eTT93eX-U6WpByP8cNMXq23HUd11j_PYj_uGjGiuP1HtT-F6v_6EAZ-wKNRquxgQVSb-1SXG6Bdr72e9a8ZeZNKKe4niBHzWNKZ_mOPe3sF79PD6H2PnQ24JqvqgXnKtZYX7ntmBmr6FTjOPu8bEdJ2Yzxj9N1WswUFS9y1v_KKqVuZoe2qu73xqnrfVffP8fC77jbg==
```

### Screenshots

![image](https://github.com/user-attachments/assets/3c680be9-a358-434f-b7e5-ab45f8378aa2)

**Comment by moxaj** [comment]
After an update on the beta branch, now the gems affect `Abberath's Fury`, however, now none of the enabling checkboxes show the damage increase. They work for `Lightning Bolt` though.

**Comment by LocalIdentity** [comment]
Fixed on dev for the next release
![image](https://github.com/user-attachments/assets/6827a473-57ee-4b65-95ed-45fc6f4aa01f)

**Comment by moxaj** [comment]
@LocalIdentity can still reproduce in latest beta
![image](https://github.com/user-attachments/assets/6025f26b-80d2-41c9-93c7-b22aae98b3eb)

`Lightning Bolt`, granted by the kalguuran enchant, cannot be supported by `Increased Critical Damage`.

**Comment by moxaj** [comment]
@LocalIdentity still happens periodically with the latest build. Support gems randomly stop applying, restarting fixes it. Please reopen.
